### ISSUE TITLE
How to disable cropped images ?

### ISSUE THREAD

**Issue by gfontaniere** [hypeJunction/hypeApps#2]
Where can i disable cropped images ?

Thank you very much.

**Comment by hypeJunction** [comment]
What do you mean? Images are cropped by default to suit Elgg's icon system. If you don't want it cropped, define custom sizes, or use 'master'.

**Comment by gfontaniere** [comment]
Sorry for my lack of knowledge, but where can i modify custom size ? which file ?

**Comment by hypeJunction** [comment]
You don't modify anything. You create your own plugin and use the hooks.

**Comment by gfontaniere** [comment]
ok. i wil see. thank u
