### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by NoobyNoob1966** [hypeJunction/hypeApps#6]
Hi
When activating plugin on Elgg 1.8.20 I get "Fatal error: Class 'hypeJunction\Integration' not found in /var/www/sitedemo.com/public/mod/hypeApps/lib/autoloader.php on line 18"

Elgg 1.8.20 and PHP 5.5.28

Any Idea?
Thanks.

**Comment by hypeJunction** [comment]
Did you download the latest release from https://github.com/hypeJunction/hypeApps/releases?

**Comment by NoobyNoob1966** [comment]
I did download from main repository, I'll try link you posted and report back.
Thank you.

**Comment by NoobyNoob1966** [comment]
I'm downloading 4.2.10 release.

**Comment by hypeJunction** [comment]
As suggested in the readme, either use composer or self-contained release.
Downloading directly from master does not include the dependencies.

**Comment by NoobyNoob1966** [comment]
Cool, Downloading release worked.
Thank you so much

Is it same with other of your plugins?
I downloaded HypeScraper and getting "hypeScraper can not resolve composer dependencies. Run composer install"
I want to use HypeWall and HypeDropzone
Just download self-contained release?

Thank you.

**Comment by hypeJunction** [comment]
I have transitioned everything to composer-driven dependency management,
and now automating releases. Not all plugins have been automated yet, it's
a bit of a boring routine, so I am doing in on as needed basis.

**Comment by hypeJunction** [comment]
I am closing. Please reopen if this persists with latest release.
