### ISSUE TITLE
is getSrcCompressionOpts() necessary in the imageservice?

### ISSUE THREAD

**Issue by Daltonstudio** [hypeJunction/hypeApps#8]
Starting to work on my site again I'm trying to get the quirks out of hypeGallery.
I noticed that with hypeApps used as the imageservice it compresses the original and thereby losing exif-information.

Do we need to alter the original?
My solution now is to replace this line

`			if ($this->simpletype == 'image') {
				$img = new \hypeJunction\Files\Image($this->tmp_name);
				$img->save($filehandler->getFilenameOnFilestore(), hypeApps()->config->getSrcCompressionOpts());
			} else {
				move_uploaded_file($this->tmp_name, $filehandler->getFilenameOnFilestore());
			}`

with 

`move_uploaded_file($this->tmp_name, $filehandler->getFilenameOnFilestore());`

in classes/hypeJunction/Files/Upload.php (l:88) which now preserves the original as it was.
I rather not alter the original plugin, do you have any suggestion to do this in a separate plugin?

**Comment by hypeJunction** [comment]
You can make a PR, I will merge it. hypeApps is not going to see much more love from me. I have rolled in all of its features into core, so it's a matter of updating other plugins to use core APIs now.

**Comment by Daltonstudio** [comment]
I'll do that later, thanks.
I figured that. I was looking into it today, but the core API wasn't very clear to me yet.
